project:
  type: website
  # render:
  #   - "!src/"

website:
  title: "Skrub learning materials"
  favicon: "images/skrub.svg"
  site-url: "https://skrub-data.org/skrub-materials/"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: pages/slides/index_slides.qmd
        text: Slides
      - href: pages/notebooks/index_notebooks.qmd
        text: Notebooks
      - href: https://skrub-data.org/stable/auto_examples/index.html
        text: Skrub Examples Gallery
      - href: pages/listings.qmd
        text: Latest updates
execute:
  freeze: auto

format:
  html:
    theme: united
    css: styles.css
    toc: true



